coverage:
  range: 50..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 50
        threshold: 1
        base: auto
    patch:
      default:
        target: 50
        threshold: 1
        base: auto
