version: "3.7"

services:
  koffee-backend:
    container_name: "Koffee-Backend"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=yeger.eu
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=yeger.eu
      - LETSENCRYPT_EMAIL=janmueller3698@gmail.com
    depends_on:
      - mongodb
      - nginx-proxy
      - nginx-proxy-companion
    restart: unless-stopped
    networks:
      - koffee-network
  mongodb:
    container_name: "MongoDB"
    image: mongo
    restart: unless-stopped
    networks:
      - koffee-network
  nginx-proxy:
    container_name: "nginx-proxy"
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: volume
        source: nginx-data
        target: /etc/nginx/certs
      - type: volume
        source: nginx-data
        target: /etc/nginx/vhost.d
      - type: volume
        source: nginx-data
        target: /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    networks:
      - koffee-network
  nginx-proxy-companion:
    container_name: "nginx-proxy-companion"
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - type: volume
        source: nginx-data
        target: /etc/nginx/certs
      - type: volume
        source: nginx-data
        target: /etc/nginx/vhost.d
      - type: volume
        source: nginx-data
        target: /usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=janmueller3698@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    networks:
      - koffee-network

volumes:
  nginx-data:

networks:
  koffee-network:
