version: "3.7"

services:
  koffee:
    container_name: koffee
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./environments/domain.env
      - ./environments/koffee.env
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - koffee-network
    secrets:
      - koffee_secret
  mongo:
    container_name: mongo
    image: mongo@sha256:cf5bf281ad2e055a5ca33c3a2f58c30b6b3ad4af8fea0066690ed7b3968f9b54
    restart: unless-stopped
    networks:
      - koffee-network
  letsencrypt:
    image: linuxserver/letsencrypt@sha256:08641e5601ee05bbc91e08be00c3959247a552390262e7368e0cb51c49553952
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    env_file:
      - ./environments/domain.env
      - ./environments/letsencrypt.env
    ports:
      - 443:443
      - 80:80
    volumes:
      - type: bind
        source: ./koffee.subfolder.conf
        target: /config/nginx/proxy-confs/koffee.subfolder.conf
        read_only: true
    restart: unless-stopped
    networks:
      - koffee-network

networks:
  koffee-network:

secrets:
  koffee_secret:
    file: ./secrets/koffee.secret
