version: "3.7"

services:
  koffee:
    container_name: koffee
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - koffee-network
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    networks:
      - koffee-network
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=yeger.eu
      - VALIDATION=http
      - STAGING=true
    volumes:
      - type: bind
        source: ./koffee.subfolder.conf
        target: /config/nginx/proxy-confs/koffee.subfolder.conf
        read_only: true
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - koffee-network

networks:
  koffee-network: