version: "3.7"

services:
  koffee:
    container_name: koffee
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./environments/domain.env
      - ./environments/koffee.env
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - koffee-network
    secrets:
      - koffee_secret
  mongo:
    container_name: mongo
    image: mongo@sha256:31f6433f7cfcd2180483e40728cbf97142df1e85de36d80d75c93e5e7fe10405
    restart: unless-stopped
    networks:
      - koffee-network
  letsencrypt:
    image: linuxserver/letsencrypt@sha256:cde12402707425c199e3ce29e40bc528c13eb2015ad55b5a0610586c6b5e1498
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    env_file:
      - ./environments/domain.env
      - ./environments/letsencrypt.env
    ports:
      - 443:443
      - 80:80
    volumes:
      - type: bind
        source: ./koffee.subfolder.conf
        target: /config/nginx/proxy-confs/koffee.subfolder.conf
        read_only: true
    restart: unless-stopped
    networks:
      - koffee-network

networks:
  koffee-network:

secrets:
  koffee_secret:
    file: ./secrets/koffee.secret
