version: "3.7"

services:
  koffee:
    container_name: koffee
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./environments/domain.env
      - ./environments/koffee.env
    ports:
      - 8080:8080
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - koffee-network
    secrets:
      - koffee_secret
  mongo:
    container_name: mongo
    image: mongo@sha256:c46e1f6dd8ac3f8592b53fa2dfdc0f7e26055929e6bf30975838ca0406c5bc2a
    restart: unless-stopped
    networks:
      - koffee-network

networks:
  koffee-network:

secrets:
  koffee_secret:
    file: ./secrets/koffee.secret
