version: "3.7"

services:
  koffee:
    container_name: koffee
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./environments/domain.env
      - ./environments/koffee.env
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - koffee-network
    secrets:
      - koffee_secret
  mongo:
    container_name: mongo
    image: mongo@sha256:8ac5e14d9badded42bcbad612a43bb28ae1bb7e411d2965588dfff83087c5aac
    restart: unless-stopped
    networks:
      - koffee-network
  letsencrypt:
    image: linuxserver/letsencrypt@sha256:1984ae375366b57d2bc2a1676b96e6371393085e9a388ac6fdb8841dbc147fdc
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    env_file:
      - ./environments/domain.env
      - ./environments/letsencrypt.env
    ports:
      - 443:443
      - 80:80
    volumes:
      - type: bind
        source: ./koffee.subfolder.conf
        target: /config/nginx/proxy-confs/koffee.subfolder.conf
        read_only: true
    restart: unless-stopped
    networks:
      - koffee-network

networks:
  koffee-network:

secrets:
  koffee_secret:
    file: ./secrets/koffee.secret
