version: "3.7"

services:
  koffee:
    container_name: koffee
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./environments/domain.env
      - ./environments/koffee.env
    ports:
      - 8080:8080
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - koffee-network
    secrets:
      - koffee_secret
  mongo:
    container_name: mongo
    image: mongo@sha256:d47a22865bc2774aad4c02333ad9e9523602a611b4b793cc8315163667b16c39
    restart: unless-stopped
    networks:
      - koffee-network

networks:
  koffee-network:

secrets:
  koffee_secret:
    file: ./secrets/koffee.secret
